- name: "* roles/nginx"
  debug:
  tags: [nginx]

- name: Install the nginx packages 
  yum: name=nginx enablerepo=nginx state=present
  register: is_nginx
  tags: [nginx]

- name: Copy the nginx configuration file 
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: 
   - restart nginx
  tags: [nginx,nginx.conf]

- name: Copy the nginx default configuration file 
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: 
   - restart nginx
  tags: [nginx]

- name: Copy the nginx proxy configuration file 
  template: src=proxy.conf.j2 dest=/etc/nginx/conf.d/proxy.conf
  notify: 
   - restart nginx
  tags: [nginx]

- name: Create the configurations for sites
  template: src=site.conf.j2 dest=/etc/nginx/conf.d/{{ item['server']['file_name'] }}
  with_items: nginx_sites
  when: (nginx_sites is defined and nginx_sites|lower != 'none')
  notify: 
   - restart nginx
  tags: [nginx]

- name: mkdir /var/log/nginx/server_name
  file: path=/var/log/nginx/{{ item['server']['server_name'] }} state=directory mode=0755 owner=omega group=omega
  with_items: nginx_sites
  when: (nginx_sites is defined and nginx_sites|lower != 'none')
  notify: 
   - restart nginx
  tags: [nginx]


# for local server
- include: local.yml
  when: (nginx_local_server is defined and nginx_local_server == 1)

# for sandbox server
- include: sandbox.yml
  when: (nginx_sandbox_server is defined and nginx_sandbox_server == 1)

# for staging server
- include: staging.yml
  when: (nginx_staging_server is defined and nginx_staging_server == 1)

# for production server
- include: prod.yml
  when: (nginx_prod_server is defined and nginx_prod_server == 1)
