- name: "* roles/nginx with nginx_prod_server"
  debug:
  tags: [nginx, nginx_prod]

- name: mkdir /etc/nginx/conf.d/include
  file: path=/etc/nginx/conf.d/include state=directory mode=0755
  when: (nginx_prod_server is defined and nginx_prod_server == 1)
  notify: 
   - restart nginx
  tags: [nginx, nginx_prod]

- name: Copy common configuration file 
  template: src=include/common-prod.conf.j2 dest=/etc/nginx/conf.d/include/common-prod.conf
  when: (nginx_prod_server is defined and nginx_prod_server == 1)
  notify: 
   - restart nginx
  tags: [nginx, nginx_prod, nginx_prod_common]

- name: Copy the nginx default configuration file 
  template: src=default.conf.prod.j2 dest=/etc/nginx/conf.d/default.conf
  when: (nginx_prod_server is defined and nginx_prod_server == 1)
  notify: 
   - restart nginx
  tags: [nginx, nginx_prod]

