- name: "* roles/test templates"
  debug:
  tags: [templates]

- name: with_first_found
  #template: src={{ item }} dest=/etc/hosts group=root owner=root mode=0644
  debug: vars={{ item }}
  with_first_found:
    - files:
        - hosts.{{ inventory_hostname }}.j2
        - hosts.{{ ansible_hostname }}.j2
        - hosts.{{ group_names[3] | default('x') }}.j2
        - hosts.{{ group_names[2] | default('x') }}.j2
        - hosts.{{ group_names[1] | default('x') }}.j2
        - hosts.{{ group_names[0] | default('x') }}.j2
        - hosts.j2
      paths:
        - ../templates/
  tags: [templates]

