---

# Nginx Default http params 
nginx_http_pre_params:
  charset:           "utf-8"
nginx_http_params:
  sendfile:          "on"
  tcp_nopush:        "on"
  tcp_nodelay:       "on"
  keepalive_timeout: "65"
  server_tokens:     "off"
  server_names_hash_bucket_size: "64"
  include:      "/etc/nginx/mime.types"
  default_type: "application/octet-stream"
  access_log:   "/var/log/nginx/access.log"
  error_log:    "/var/log/nginx/error.log"
  gzip:              "on"
  gzip_disable:      "\"msie6\""
  gzip_vary:         "on"
  gzip_proxied:      "any"
  gzip_comp_level:   "2"
  gzip_buffers:      "4 8k"
  gzip_http_version: "1.0"
  gzip_types: "text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/x-http-php"
  proxy_cache_path: "/var/cache/nginx levels=1:2 keys_zone=czone:32m max_size=256m inactive=120m"
#  proxy_temp_path:  "/var/tmp/nginx" # directive is duplicate
  proxy_cache_key:  "\"$scheme://$host$request_uri\""
  "proxy_set_header Connection":         "\"\""
  "proxy_set_header Host":               "$host"
  "proxy_set_header X-Real-IP":          "$remote_addr"
  "proxy_set_header Remote-Addr":        "$remote_addr"
  "proxy_set_header X-Forwarded-Host":   "$host"
  "proxy_set_header X-Forwarded-Server": "$host"
  "proxy_set_header X-Forwarded-For":    "$proxy_add_x_forwarded_for"
#  proxy_connect_timeout: "30" # directive is duplicate
  proxy_send_timeout:    "30"
  proxy_read_timeout:    "60"
#  proxy_buffers:         "32 16k" # directive is duplicate
  proxy_headers_hash_max_size:    "1024"
  proxy_headers_hash_bucket_size: "128"


# @TODO default server
nginx_sites:
 - server:
    file_name: foo
    listen: 8080
    server_name: localhost
    root: "/tmp/site1"
    location1: {name: /, try_files: "$uri $uri/ /index.html"}
    location2: {name: /images/, try_files: "$uri $uri/ /index.html"}
 - server:
    file_name: bar
    listen: 9090
    server_name: ansible
    root: "/tmp/site2"
    location1: {name: /, try_files: "$uri $uri/ /index.html"}
    location2: {name: /images/, try_files: "$uri $uri/ /index.html"}

