# Pass in a comma-separated list of repos to use (e.g. "remi,epel").
php_enablerepo: "remi,remi-php55"
php_memory_limit: "64M"
php_max_execution_time: "60"
php_upload_max_filesize: "64M"
php_date_timezone: "Asia/Tokyo"
php_enable_webserver: true
php_webserver_daemon: "httpd"

php_enable_php_fpm: false

php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_short_open_tag: false

pre_php_packages:
  # for GD ( not in remi-php55... )
  - { name: gd-last, repo: remi }
  # for phpMyAdmin
  - { name: ImageMagick-last, repo: "remi,remi-php55,epel" }
  # for php-mcrypt
  - { name: libmcrypt, repo: epel }
  - { name: php-pecl-yaml, repo: "remi,remi-php55" }
  - { name: xhprof, repo: "remi,remi-php55" }
  # for swfed
  - { name: re2c, repo: rpmforge }
