---

# zabbix vars

# for all servers
zabbix_default_package:
  - name: zabbix-agent
    enablerepo: zabbix

# for zabbix-agent "Server" IP Address zabbix server ( omg-zabbix01 )
zabbix_agentd_conf_server: 10.35.86.144

# for zabbix-server ( maybe monitor server )
zabbix_server_default_package:
  - name: zabbix-server-mysql
    enablerepo: zabbix,epel
  - name: zabbix-web-mysql
    enablerepo: zabbix,epel
  - name: zabbix-web-japanese
    enablerepo: zabbix,epel
  - name: zabbix-get
    enablerepo: zabbix,epel
  # for zabbix. it is not mysql-comunity-server...
  - name: mysql-server
    enablerepo: zabbix,epel
  # for ansible. it is use ansible mysql_XX actions
  - name: MySQL-python
    enablerepo: zabbix,epel

# zabbix schema dir
zabbix_db_intial_dir: /usr/share/doc/zabbix-server-mysql-2.4.3/create/

# zabbix-server MySQL config
zabbix_db_host: localhost
zabbix_db_root: root
zabbix_db_rtps: ""
zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_pass: zabbixpassword

