# see https://github.com/mmoya/ansible-playbooks/tree/master/rbenv
# 
- name: "* roles/rbenv | tags rbenv"
  debug:
  tags: [rbenv]

- name: update rbenv repo
  # git: repo=git://github.com/sstephenson/rbenv.git dest={{ rbenv_root }} version=v0.4.0 accept_hostkey=yes
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ rbenv_root }} version=v0.4.0 accept_hostkey=yes
  tags: [rbenv]

- name: add rbenv to path
  file: path=/usr/local/bin/rbenv src={{ rbenv_root }}/bin/rbenv state=link
  tags: [rbenv]

- name: mkdir versions. for rbenv install.
  file: path={{ rbenv_root }}/versions state=directory mode=0755
  tags: [rbenv]

- name: mkdir shims. for rbenv install.
  file: path={{ rbenv_root }}/shims state=directory mode=0755
  tags: [rbenv]

- name: add rbenv initialization to profile
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
  tags: [rbenv]

- name: check ruby-build installed ( ignore_errors yes )
  command: test -x /usr/local/bin/ruby-build
  register: rbuild_present
  ignore_errors: yes
  changed_when: false
  tags: [rbenv]

- name: create temporary directory
  command: mktemp -d
  register: tempdir
  when: rbuild_present|failed
  tags: [rbenv]

- name: clone ruby-build repo
  # git: repo=git://github.com/sstephenson/ruby-build.git dest={{ tempdir.stdout }}/ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ tempdir.stdout }}/ruby-build
  when: rbuild_present|failed
  tags: [rbenv]

- name: install ruby-build
  command: ./install.sh chdir={{ tempdir.stdout }}/ruby-build
  when: rbuild_present|failed
  tags: [rbenv]

- name: remove temporary directory
  file: path={{ tempdir.stdout }} state=absent
  when: rbuild_present|failed
  tags: [rbenv]

- name: check ruby {{ ruby_version }} installed ( ignore_errors yes )
  # システム依存？ /usr/local/path が入っていないと rbenv がエラー以下同文
  # shell: RBENV_ROOT={{ rbenv_root }} {{ rbenv_root }}/bin/rbenv versions | grep {{ ruby_version }}
  shell: PATH=$PATH:/usr/local/bin RBENV_ROOT={{ rbenv_root }} {{ rbenv_root }}/bin/rbenv versions | grep {{ ruby_version }}
  register: ruby_installed
  ignore_errors: yes
  changed_when: false
  tags: [rbenv]

- name: install ruby {{ ruby_version }}
  shell: PATH=$PATH:/usr/local/bin  RBENV_ROOT={{ rbenv_root }} {{ rbenv_root }}/bin/rbenv install {{ ruby_version }}
  when: ruby_installed|failed
  tags: [rbenv]

- name: set global ruby {{ ruby_version }}
  shell: RBENV_ROOT={{ rbenv_root }} {{ rbenv_root }}/bin/rbenv global {{ ruby_version }}
  when: ruby_installed|failed
  tags: [rbenv]

- name: rehash
  shell: RBENV_ROOT={{ rbenv_root }} {{ rbenv_root }}/bin/rbenv rehash
  when: ruby_installed|failed
  tags: [rbenv]

- name: set gemrc
  copy: src=gemrc dest=/root/.gemrc owner=root group=root mode=0644
  tags: [rbenv]

- name: check compass installed ( ignore_errors yes )
  shell: PATH=$PATH:/usr/local/bin RBENV_ROOT={{ rbenv_root }} {{ rbenv_root }}/bin/rbenv exec gem list | grep compass
  register: compass_installed
  ignore_errors: yes
  changed_when: false
  tags: [rbenv]

- name: compass | install
  shell: PATH=$PATH:/usr/local/bin RBENV_ROOT={{ rbenv_root }} {{ rbenv_root }}/bin/rbenv exec gem install compass
  when: compass_installed|failed
  tags: [rbenv]

- name: compass | path
  file: src=/usr/local/rbenv/shims/rake dest=/usr/local/rbenv/shims/compass state=link force=yes
  when: compass_installed|failed
  tags: [rbenv]

- name: sass | path
  file: src=/usr/local/rbenv/shims/rake dest=/usr/local/rbenv/shims/sass state=link force=yes
  when: compass_installed|failed
  tags: [rbenv]
